// Runs the ported checks. `swift run CoreChecks` — exits non-zero on the first failing case.
SessionNameTests.run()
SessionLedgerTests.run()
TaskWordsTests.run()
ShellPathTests.run()
FigmaStatusTests.run()
PanelConfigTests.run()
PanelPiecesTests.run()
TabStateTests.run()
StatusLineTests.run()
StatusRingTests.run()
ExitRecoveryTests.run()
PromptDetectorTests.run()
FigmaMenuTests.run()
ProcessOutputTests.run()
Checks.report()
